<a href="https://colab.research.google.com/github/braddugg/DSFEB12/blob/main/Python_Day_1_Feb_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("My Name is Brad")

My Name is Brad


In [3]:
# COMMENT
# Enter - It goes to next line within same code block
# Shift + Enter - It executes this code block and goes to next code block
# Alt + Enter - It executes this code block and creates a new code block
# Ctrl + Enter - It executes this code block

In [4]:
#TYPES OF BRACKETS
#[] - data extraction/slicing of data, lists
#{}  - dictionaries/sets
#() - methods/functions, tuples

In [5]:
x = 20

In [6]:
x

20

In [7]:
type(x)

int

In [8]:
y = 'brad'
type(y)

str

In [9]:
z = 13.5
type(z)

float

In [10]:
a = True
type(a)

bool

In [11]:
#DATA TYPES 
#string - character or alphabet
#float - decimal 
#integer - number
#boolean - logical - True or False


In [12]:
print(20+10)
print(100-80)
print(990/99)
print(85*10)

30
20
10.0
850


In [13]:
import math

In [14]:
math.sqrt(64)

8.0

In [15]:
list1 = ["Brad", 20, 13.5, True]

In [16]:
list1

['Brad', 20, 13.5, True]

In [17]:
#Index in Python starts with 0 

In [18]:
list1[1] 

20

In [19]:
list1[1] = 40
list1

['Brad', 40, 13.5, True]

In [20]:
a = "Good Morning"

In [21]:
b = "Brad"

In [22]:
a+b

'Good MorningBrad'

In [23]:
a+" "+b

'Good Morning Brad'

In [24]:
10+20

30

In [25]:
7 > 5

True

In [26]:
20 < 18

False

In [29]:
i = 0
while i <= 10:
  print(i)
  i = i+1
print('Python is Good')

0
1
2
3
4
5
6
7
8
9
10
Python is Good


In [30]:
range(6)

range(0, 6)

In [31]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
#Indexing Starts from 0 and Ends with Last Value -1

In [32]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [35]:
for i in range(6):
  print(i)
print("Python is Okay")

0
1
2
3
4
5
Python is Okay


In [10]:
import numpy as np
from numpy.random import randn, randint

In [2]:
x = randn()
if x >1:
  result = "Greater Than 1"
print(x)
print(result)

0.9077961388920923


NameError: ignored

In [4]:
result = None
x = randn()
if x >1:
  result = "Greater Than 1"
print(x)
print(result)

2.560800215012673
Greater Than 1


In [12]:
result = None
x = randn()
if x >1:
  result = "Greater Than 1"
elif x <-1:
  result = "Less Than -1"
else:
  result = "Between -1 and 1"
print(x)
print(result)

-1.9175013016096552
Less Than -1


In [13]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [14]:
type(list1)

list

In [15]:
list(range(1,51,3))

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [16]:
list2 = list(range(1,51,3))

In [17]:
list2[1]

4

In [18]:
list2[-1]

49

In [19]:
tuple1 = (12,36,72)

In [20]:
tuple1[1]

36

In [21]:
tuple1[1] = 48

TypeError: ignored

In [22]:
list3 = [12,36,72]

In [23]:
list3[1] = 48

In [24]:
list3

[12, 48, 72]

In [25]:
import numpy as np

In [26]:
list5 = ['a', 20,30.5, True]

In [28]:
np.array(list5)

array(['a', '20', '30.5', 'True'], dtype='<U32')

In [29]:
list6 = [20,30.5, True]
np.array(list6)

array([20. , 30.5,  1. ])

In [30]:
list7 = [20, True]
np.array(list7)

array([20,  1])

In [32]:
list8 = [True]
np.array(list8)

array([ True])

In [33]:
# data types hierarchy - string, float, integer, boolean

In [34]:
dict1 = {'Index0':'Emp No.', 'Index1':'Emp.Name', 'Index2':'Salary'}

In [35]:
dict1

{'Index0': 'Emp No.', 'Index1': 'Emp.Name', 'Index2': 'Salary'}

In [36]:
dict1['Index2']

'Salary'